development: &DEVELOPMENT
  adapter: postgresql
  database: gemcutter_development
  username: postgres
  host: postgres
  port: 5432
  pool: 5
  timeout: 5000

staging:
  <<: *DEVELOPMENT

test: &TEST
  <<: *DEVELOPMENT
  database: gemcutter_test
  min_messages: warning

production:
  adapter: postgresql
  database: gemcutter_production
