#!/bin/bash

pushd /rubygems.org

bundle install --path /vender/bundle

cp /scripts/load-pg-dump .
cp /scripts/database.yml ./config/
./load-pg-dump -h postgres -p 5432 -c -d gemcutter_development dump

popd
