#!/bin/sh

# variables
public_tar=
pg_database=rubygems
pg_user=postgres
pg_host=127.0.0.1
pg_port=5432
download=false


## For downloading
base_url="https://s3-us-west-2.amazonaws.com/rubygems-dumps/"
prefix="production/public_postgresql"

OPTIND=1
while getopts "h:cd:u:p:" opt; do
    case "$opt" in
        h)  pg_host=$OPTARG
            ;;
        c)  download=true
            ;;
        d)  pg_database=$OPTARG
            ;;
        u)  pg_user=$OPTARG
            ;;
        p)  pg_port=$OPTARG
            ;;
        '?')
            show_help >&2
            exit 1
            ;;
    esac
done
shift "$((OPTIND-1))" # Shift off the options and optional

public_tar=$1
if [ -z "$public_tar" ]; then
  show_help >&2
  exit 1
fi

if $download; then
  key=$(curl -s "${base_url}?prefix=${prefix}" | sed -ne 's/.*<Key>\(.*\)<\/Key>.*/\1/p')
  latest_url="${base_url}${key}"
  echo "Downloading ${latest_url} to ${public_tar}"
  curl --progress-bar "${latest_url}" > ${public_tar}
fi

printf 'Loading "%s" into database "%s" as user "%s"\n', "$public_tar", "$pg_database", "$pg_user"

bundle exec rake db:drop
bundle exec rake db:create

echo "Adding hstore extension"
psql -q -U $pg_user -h $pg_host -p $pg_port -d $pg_database -c "CREATE EXTENSION IF NOT EXISTS hstore;"

echo "Running migrations"
bundle exec rake db:migrate

# Extract the single PostgresSQL.sql.gz file from the tar file, pass it through gunzip
# and load it as quietly as possible into the database
echo "Loading the data from $public_tar"
tar xOf $public_tar public_postgresql/databases/PostgreSQL.sql.gz | \
  gunzip -c | \
  psql --username $pg_user --dbname $pg_database -h $pg_host -p $pg_port

echo "Done."
