FROM ruby:2.3.5

RUN apt-get update && apt-get install -y postgresql nodejs
RUN gem i bundler
RUN git clone https://github.com/rubygems/rubygems.org.git

RUN gem install nokogiri -v '1.8.2'
RUN gem install nio4r -v '2.0.0'
RUN gem install bcrypt -v '3.1.11'
RUN gem install unf_ext -v '0.0.7.4'
RUN gem install ffi -v '1.9.23'
RUN gem install pg -v '0.21.0'
RUN gem install msgpack -v '1.2.4'
RUN gem install websocket-driver -v '0.6.5'
RUN gem install bootsnap -v '1.3.0'
RUN gem install hitimes -v '1.2.5'
RUN gem install kgio -v '2.11.0'
RUN gem install rainbow -v '2.2.2'
RUN gem install raindrops -v '0.18.0'
RUN gem install rbtrace -v '0.4.10'
RUN gem install unicorn -v '5.3.0'

CMD ['/bin/bash']
